### ISSUE TITLE
The code in Ch. 7 is not working

### ISSUE THREAD

**Issue by cheukpong2014** [PacktPublishing/Odoo-11-Development-Essentials-Third-Edition#1]
I have installed the todo_app in Ch. 3 and todo_stage in Ch. 6. They are all fine. But the todo_wizard in Ch. 7   doesn't make any effect to the todo_app. Please kindly check.

**Comment by cheukpong2014** [comment]
The code is no problem. I have made mistake. Sorry.

**Comment by techsachinkumar** [comment]
Closing the issue as there is no problem in the code.
